spring:
  datasource:
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432}/${RESTAURANT_DB_NAME:postgres}
    username: ${RESTAURANT_DB_USER:postgres}
    password: ${RESTAURANT_DB_PASSWORD:123}
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:my-secret-key}

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:dww76dcbp}
  api_key: ${CLOUDINARY_API_KEY:698886128929873}
  api_secret: ${CLOUDINARY_API_SECRET:CfWpVWCogzBtY89Li4y2B5xbz7I}