spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: restaurant
    datasource:
      url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432}/${RESTAURANT_DB_NAME:postgres}
      username: ${RESTAURANT_DB_USER:postgres}
      password: ${RESTAURANT_DB_PASSWORD:123}
      driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
server:
  port: ${SERVER_PORT:8080}
