spring:
  datasource:
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432}/${RESTAURANT_DB_NAME:postgres}
    username: ${RESTAURANT_DB_USER:postgres}
    password: ${RESTAURANT_DB_PASSWORD:123}

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:my-secret-key}