version: "3.9"
services:
  postgress:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

  sonarqube:
    container_name: sonarqube
    image: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_USERNAME=postgres
      - SONARQUBE_JDBC_PASSWORD=1234
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgress:5432/postgres
    depends_on:
      - postgress