version: "3.9"
services:
  postgress:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
  postgreskeycloak:
    container_name: postgres-keycloak
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_ADDR=postgres-keycloak
      - DB_DATABASE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=1234